version: '3.8'
services:
  react-app:
    container_name: react-app
    image: node:12.14.1
    working_dir: /app
    volumes:
      - ./app:/app
    command: >
      /bin/bash -c "npm i && npm run build"
    environment:
      REACT_APP_BASE_URL: 'http://localhost:8080'
  koa-server:
    restart: always
    container_name: koa-server
    image: node:12.14.1
    working_dir: /koa/server
    environment:
      VERSION: 1.0.0
    ports:
      - 8080:8080
    volumes:
      - .:/koa
    command: >
      /bin/bash -c "npm i && npm run prod:build && npm run prod"
